export const types = {
    CREATE_TODO: "CREATE_TODO",
    DELETE_TODO: "DELETE_TODO",
    CHANGE_STATUS: "CHANGE_STATUS",
    UPDATE_TODO: "UPDATE_TODO",
    DELETE_TODOS: "DELETE_TODOS",
    GET_TODOS_LS: "GET_TODOS_LS",
    CHANGE_TITLE_FROM_INPUT: "CHANGE_TITLE_FROM_INPUT",
    CHANGE_TITLE: "CHANGE_TITLE"
}